In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Numbers ##

Textbook section 4.1

In [2]:
3 * 30 # int

90

In [3]:
10 / 3 # float

3.3333333333333335

In [4]:
3 / 3 # float

1.0

In [5]:
10 ** 3 # 10 * 10 * 10 

1000

In [6]:
10 ** 0.5 # float

3.1622776601683795

In [ ]:
12345678 ** 890

In [9]:
75892745.215489247589274985712 - 75892745.21548925

0.0

In [10]:
10 / 5

2.0

In [11]:
int(10 / 5)

2

In [12]:
16 / 30

0.5333333333333333

In [13]:
round(16 / 30), int(16 / 30)

(1, 0)

In [14]:
float(3)

3.0

## Strings ##

Textbook section 4.2

In [15]:
'Flavor'

'Flavor'

In [16]:
"Flavor"

'Flavor'

In [ ]:
Flavor

In [18]:
'straw' + 'berry'

'strawberry'

In [23]:
flavor = 'strawberry'
print('The flavor you chose is ' + flavor + '.')

The flavor you chose is strawberry.


In [ ]:
5 + '5'

In [24]:
cost = 2.50
print('The cost is ' + str(cost) + '.')

The cost is 2.5.


In [20]:
5 + int('5')

10

In [21]:
'yelp review: ' + str(10)

'yelp review: 10'

In [22]:
str(int('10'))

'10'

## Arrays ##

Textbook section 5.1

In [25]:
my_array = make_array(1, 2, 3)
my_array

array([1, 2, 3])

In [26]:
type(my_array)

numpy.ndarray

In [27]:
len(my_array)

3

In [28]:
# Add a constant value to each element of the array
my_array + 2

array([3, 4, 5])

In [30]:
# Just like with tables, the original array is not modified
my_array

array([1, 2, 3])

In [31]:
# Store the resulting array in a new variable if you want to use it later
my_array_plus_two = my_array + 2
my_array_plus_two

array([3, 4, 5])

In [32]:
my_array * 2

array([2, 4, 6])

In [33]:
my_array ** 2

array([1, 4, 9])

In [34]:
my_array_2 = make_array(-1, -2, -1)
my_array_2

array([-1, -2, -1])

In [35]:
# Adding two arrays adds them together term by term
my_array_2 + my_array

array([0, 0, 2])

In [36]:
my_array_3 = make_array(1,2,3,4)
my_array_3

array([1, 2, 3, 4])

In [ ]:
my_array + my_array_3

In [38]:
names_array = make_array('Andrew', 'Conan', 'Jonathan')
names_array

array(['Andrew', 'Conan', 'Jonathan'],
      dtype='<U8')

In [39]:
# .item accesses individual items in the array
names_array.item(0)

'Andrew'

In [40]:
names_array.item(1)

'Conan'

In [ ]:
names_array.item(3)

### Practice 1

The past weeks temperatures in Fahrenheit were:
70, 68, 66, 71, 72, 70, 68

The connection between Fahrenheit temperature F and Celsius temperature C is:
C = 5/9(F - 32)

Use an array calculation to convert all these Fahrenheit temperatures to Celsius.

In [49]:
fahrenheit = make_array(70, 68, 66, 71, 72, 70, 68)
print(fahrenheit)
Celsius = 5/9 * (fahrenheit - 32)
print(Celsius)

[70 68 66 71 72 70 68]
[ 21.11111111  20.          18.88888889  21.66666667  22.22222222
  21.11111111  20.        ]


### Practice 2

A lemonade stand sold
- 50 cups of lemonade at $3.50 each
- 35 bottles of water at $2.00 each
- 25 cookies at $3.00 each

Create an array for sales and an array for cost. Use these to produce a third array for revenue generated by each item (lemonade revenue in the first entry, water revenue in the second, and cookie revenue in the third).

In [54]:
sales = make_array(50, 35, 25)
cost = make_array(3.50, 2.00, 3.00)
revenue = sales * cost
print(revenue)

[ 175.   70.   75.]


## Functions on Arrays ##

Textbook section 5.1 (lots more functions there)

In [56]:
nums = make_array(0, 1, 3, 5, 7)
nums

array([0, 1, 3, 5, 7])

In [57]:
np.count_nonzero(nums)

4

In [58]:
np.sum(nums)

16

In [59]:
np.diff(nums)

array([1, 2, 2, 2])

In [60]:
np.mean(nums)

3.2000000000000002

In [61]:
decimals = make_array(1.123, 3.123, 5.123, 7.678)
rounded = np.round(decimals, 2)
rounded

array([ 1.12,  3.12,  5.12,  7.68])

## Improved Practice Problems

In [65]:
round_cel = np.round(Celsius, 1)
print(round_cel)

sum_rev = np.sum(revenue)
print(sum_rev)

[ 21.1  20.   18.9  21.7  22.2  21.1  20. ]
320.0


# Ranges

In [66]:
# One argument gives an array from 0 to the integer provided (excluding right endpoint)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# Two arguments denotes the starting value (inclusive) and ending value (exclusive)
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [68]:
# Three arguments denotes the starting value, ending value, and step size
np.arange(5, 10, 2)


array([5, 7, 9])

# Practice

1. Use arange to generate the following approximation of $\pi$:

$$4 \cdot \left( \left(1 + \frac{1}{5} + \frac{1}{9} + \dots + \frac{1}{9997} \right) - \left(\frac{1}{3} + \frac{1}{7} + \frac{1}{11} + \dots + \frac{1}{9999} \right) \right)$$

- Use arange to generate an array containing 1, 5, 9, ... , 9997
- Use / to generate an array containing 1/1, 1/5, 1/9, ..., 1/9997
- Sum the elements of this array to get the value of the first parenthesis
- Go through a similar process to get the second parenthesis
- Calculuate the estimate

In [80]:
pie1 = 4 * (np.sum(make_array(1/np.arange(1, 9997, 4))) - np.sum(make_array(1/np.arange(3, 9999, 4))))
pie1


3.141392573559786

2. Use arange to generate the following approximation of $\pi$:
$$2 \cdot \left( \frac{2}{1} \cdot \frac{4}{3} \cdot \frac{6}{5} \cdots \frac{1,000,000}{999999} \right) \cdot \left( \frac{2}{3} \cdot \frac{4}{5} \cdot \frac{6}{7} \cdots \frac{1,000,000}{1,000,001} \right)$$

In [89]:
pie2 = 2 * (np.prod(make_array(np.arange(2, 1000000, 2)/np.arange(1, 999999, 2))) * np.prod(make_array(np.arange(2, 1000000, 2)/np.arange(3, 1000001, 2))))
pie2

3.141591082791973